runtime: python311

instance_class: F2

env_variables:
  FLASK_ENV: "production"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

handlers:
- url: /static
  static_dir: static
  secure: always
  http_headers:
    Cache-Control: "public, max-age=31536000"

- url: /.*
  script: auto
  secure: always

vpc_access_connector:
  name: projects/YOUR_PROJECT_ID/locations/YOUR_REGION/connectors/YOUR_CONNECTOR_NAME